### ISSUE TITLE
cache_flush call

### ISSUE THREAD

**Issue by flopperj** [a7/wpe-cache-flush#1]
Hi Aaron Holbrook,

First of all thank you so much for this solution. It's a life saver :) 

One thing I wanted to point out was that the cache_flush logic was not quite working for me. The WpeCommon purge_memcached, clear_maxcdn_cache and purge_varnish_cache calls were not being hit. I modified that block of code to the following and it worked:
```

    if ( method_exists('WpeCommon', 'purge_memcached' ) ) {
        \WpeCommon::purge_memcached();
    }

    if ( method_exists('WpeCommon', 'clear_maxcdn_cache' ) ) {
        \WpeCommon::clear_maxcdn_cache();
    }

    if ( method_exists('WpeCommon', 'purge_varnish_cache' ) ) {
        \WpeCommon::purge_varnish_cache();
    }
```

**Comment by interactiveRob** [comment]
Hi Aaron, Thanks for creating this! super useful. 
I second your comment @flopperj. I could verify that the WpeCommon namespace existed, but as you mentioned those calls weren't getting hit. After reading the mu-plugins source, it looks like we can use the built in wpe_param() function to flush, here's what worked for me (logging included):
```
	if ( function_exists( 'wpe_param' ) ) {
		wpe_param( 'purge-all' );
		error_log("All Caches were purged!");
	}
```

**Comment by mattkeys** [comment]
@interactiveRob 

From my reading of the mu-plugins source, the wpe_param() function just returns true or false if a key exists in $_REQUEST. So your code would not flush the caches.

To actually flush the caches using the WPEngine Common plugins functionality, this is what worked for me:

```
$flush_url = add_query_arg(
	'wp-cmd',
	'purge-all-caches',
	home_url()
);
$response = wp_remote_get( $flush_url );
```

This seems a bit easier and hopefully a bit more future proof compared to what is used in this plugin.

You can optionally log the $response (possibly along with wp_remote_retrieve_body() or wp_remote_retrieve_response_code() depending on your needs).

Doing this on my WPEngine site I see a 200 response with body: "All Caches were purged!".

This code must be performed on an 'approved' IP address, so any IP associated with WPEngine servers. If this code is running on your WPEngine site you are fine. If not you could spoof the $_SERVER['REMOTE_ADDR'] that is being used to validate IPs.
